stages:
  - stage: Dev
    jobs:
    - job: DevJob
      steps:
      - script: echo DevJob

  - stage: QA
    dependsOn: Test    # this stage runs after Dev
    jobs:
    - job: QAJob
      steps:
      - script: echo QAJob

  - stage: Perf
    dependsOn: Test    # this stage runs in parallel with QA, after Dev
    jobs:
    - job: PerfJob
      steps:
      - script: echo PerfJob

  - stage: Prod
    dependsOn:         # this stage runs after QA and Perf
    - Perf
    - QA
    jobs:
    - job: ProdJob
      steps:
      - script: echo ProdJob