stages:
  - stage: Dev
    jobs:
    - job: DevJob
      steps:
      - script: echo DevJob

  - stage: QA
    dependsOn: Dev    # this stage runs after Dev
    jobs:
    - job: QAJob
      steps:
      - script: echo QAJob

  - stage: Perf
    dependsOn: Dev    # this stage runs in parallel with QA, after Dev
    jobs:
    - job: PerfJob
      steps:
      - script: echo PerfJob

  - stage: Prod
    dependsOn:         # this stage runs after QA and Perf
    - Perf
    - QA
    jobs:
    - deployment: ProdJob
      environment: prodEnv
      strategy:
        runOnce:
          deploy:                    
            steps:
            - script: echo ProdJob